name: Semgrep

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install semgrep
          semgrep --version

      - name: Run Semgrep (SARIF)
        run: |
          semgrep scan \
            --config p/javascript \
            --config p/typescript \
            --sarif -o semgrep.sarif

      - name: Run Semgrep (JSON)
        run: |
          semgrep scan \
            --config p/javascript \
            --config p/typescript \
            --json -o semgrep.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: |
            semgrep.sarif
            semgrep.json